### ISSUE TITLE
auth0 instance is null to due invalid use of getContext

### ISSUE THREAD

**Issue by carloslenz** [dopry/svelte-auth0#10]
I'm getting this error `TypeError: Cannot read property 'loginWithRedirect' of undefined at login (auth0.js)` (90% of the time), so I started looking for the problem. Turns out [Svelte Docs](https://svelte.dev/docs#getContext) say getContext _Must be called during component initialisation._ So I think all uses of getContext in auth0.js functions are not supported.

**Comment by dopry** [comment]
should be resolved in 32494616cd3847129fc4349135063ac785ff4082 and [1.0.0 npm release](https://www.npmjs.com/package/@dopry/svelte-auth0/v/1.0.0). reopen if this persists.
