### ISSUE TITLE
Unhandled Promise Rejection: Error: Function called outside component initialization

### ISSUE THREAD

**Issue by urosgruber** [dopry/svelte-auth0#11]
I was trying a demo site and upgrade Svelte to the latest version, but after clicking to a login button I get an error 
"Unhandled Promise Rejection: Error: Function called outside component initialization"

I tried with reverting svelte version and I can see that version 3.24.1 works but it's broken on 3.25.x onwards.

Steps to reproduce
- update package.json with 3.25.0
- `npm i`
- `npm run showcase:dev`
- open browser and click login

**Comment by dopry** [comment]
should be resolved in 32494616cd3847129fc4349135063ac785ff4082 and [1.0.0 npm release](https://www.npmjs.com/package/@dopry/svelte-auth0/v/1.0.0). reopen if this persists.
