### ISSUE TITLE
not a valid SSR component

### ISSUE THREAD

**Issue by simoncpu** [dopry/svelte-auth0#4]
I tried importing this into Sapper but I get this error:

`Error: &lt;Auth0Context&gt; is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules`

I tried doing `npm install -D` and I got more errors instead. Any tips on how to use this with Sapper? Thanks!

**Comment by dopry** [comment]
Good question. I never tested with SSR.  Normally, when I'm doing SSR setup conditionals to not render stuff that wouldn't work with SSR.  How do you expect to use Auth0Context with SSR?

**Comment by leonkalema** [comment]
Am using dirty way for on svelte sapper to have this rendered when using SSR, 

`{#if process.browser}
  <Auth0Context
    .....
  </Auth0Context>
{/if}`


That should work :)
